# Generated by Django 2.0.7 on 2018-11-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaana', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.TextField(default='', max_length=50000),
        ),
    ]
